### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by rosariopfernandes** [hoitab/TFLClassify#1]
Running the code from this repo (the `finish` module) throws the following exception during runtime:
```
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.tensorflow.lite.examples.classification, PID: 20474
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: ToTensorConverter: input data size does not match expected size.
    Node number 63 (TfLiteGpuDelegateV2) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.support.model.Model.run(Model.java:263)
        at org.tensorflow.lite.examples.classification.ml.NewPokemonModel.process(NewPokemonModel.java:76)
        at org.tensorflow.lite.examples.classification.MainActivity$ImageAnalyzer.analyze(MainActivity.kt:225)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:376)
        at androidx.camera.core.-$$Lambda$ImageAnalysis$qO2F3Tn7pfTvGyL-EvT8WWE0F0w.analyze(Unknown Source:4)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:87)
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$g-dcm6aZmGod2IWKPwN4CArIZzI.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

As mentioned on the log, it comes from `MainActivity.kt` line 225:
https://github.com/hoitab/TFLClassify/blob/b7e22f7485c868ebc820dad409229d8f687bcb7b/finish/src/main/java/org/tensorflow/lite/examples/classification/MainActivity.kt#L225

**Comment by rosariopfernandes** [comment]
Seems like a problem with GPU Acceleration. I've disabled it and the app runs just fine :)

**Comment by hoitab** [comment]
Interesting. Can you please try something for me?

In the Build.gradle file, can you please try replacing the GPU import line with this:

` implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly'`

And in the MainActivity where we initiate the options object, can you please put in the following?
```
        // TODO 6. Optional GPU acceleration`
        private val compatList = CompatibilityList()`
        private val options = if(compatList.isDelegateSupportedOnThisDevice){
            Log.d(TAG, "Enabling GPU")
            Model.Options.Builder().setDevice(Model.Device.GPU).build()
        } else {
            Log.d(TAG, "Enabling 3 threads")
            Model.Options.Builder().setNumThreads(3).build()
        }

        // TODO 1: Add class variable TensorFlow Lite Model
        private val flowerModel = FlowerModel.newInstance(ctx , options)
```

This is an experimental GPU device compatibility list. I want to see if that is working for your phone.

Can you also send me your phone maker and model and the version of Android you are running? DM me on Twitter hoitab@ if it is easier.

**Comment by rosariopfernandes** [comment]
@hoitab I'm using a LG G5, Android 8.0.0

After updating the code with the snippet you provided an exception is thrown:
```
2020-07-03 21:15:16.696 22432-22679/org.tensorflow.lite.examples.classification E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: org.tensorflow.lite.examples.classification, PID: 22432
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
    Node number 63 (TfLiteGpuDelegateV2) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:154)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.support.model.Model.run(Model.java:263)
        at org.tensorflow.lite.examples.classification.ml.FlowerModel.process(FlowerModel.java:75)
        at org.tensorflow.lite.examples.classification.MainActivity$ImageAnalyzer.analyze(MainActivity.kt:235)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:372)
        at androidx.camera.core.-$$Lambda$ImageAnalysis$qO2F3Tn7pfTvGyL-EvT8WWE0F0w.analyze(Unknown Source:4)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:87)
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$g-dcm6aZmGod2IWKPwN4CArIZzI.run(Unknown Source:8)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by hoitab** [comment]
Interesting. Thank you so much for this. I will ask my GPU delegate colleague.

**Comment by hoitab** [comment]
Actually I want to check two things:
1. `NewPokemonModel`, I am assuming that this is a TFLite model you trained using the TensorFlow Lite model maker in the codelab? The reason I asked is if it is not based on the same general graph structure, we might need a copy to test.
2. `GpuDelegate must run on the same thread where it was initialized` - I am assuming you have not changed [the single thread executer from the codelab](https://github.com/hoitab/TFLClassify/blob/main/finish/src/main/java/org/tensorflow/lite/examples/classification/MainActivity.kt#L69)?

**Comment by rosariopfernandes** [comment]
1. Yes, I trained using the TensorFlow Lite model maker. But then in my second comment, I switched back to the FlowerModel provided in the codelab, as you can see in the exception trace.
2. Correct, I did not change the executer.

**Comment by hoitab** [comment]
Thank you for you speedy reply, I will ask the team.

**Comment by iglaweb** [comment]
@hoitab Very similar exception is thrown on Google Pixel while running Blazeface model from Mediapipe repo (https://github.com/google/mediapipe/blob/master/mediapipe/models/face_detection_front.tflite). But this model worked successfully on Samsung S10 and Xiaomi MI8.

```
 Internal error: Failed to run on the given Interpreter: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
    Node number 164 (TfLiteGpuDelegateV2) failed to invoke.
    
    TfLiteGpuDelegate Invoke: GpuDele [DevelopReportingTree.log:18]
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
    Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found
    Falling back to OpenGL
    TfLiteGpuDelegate Invoke: GpuDelegate must run on the same thread where it was initialized.
    Node number 164 (TfLiteGpuDelegateV2) failed to invoke.
    
    TfLiteGpuDelegate Invoke: GpuDele
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:158)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:343)
```

**Comment by hoitab** [comment]
We might have a solution and it will be incredibly helpful if someone can verify this fix works.

Previously, the initialisation code is run when the app starts on the main thread and this can be different compare to the executor thread. To fix this, we can initialise the model by lazy so only when the process line is executed for the first time do we run the initialisation code on the same thread as the process command. 

https://github.com/hoitab/TFLClassify/blob/9ae345ba217c28ef36aef9b858d071b36004e55e/finish/src/main/java/org/tensorflow/lite/examples/classification/MainActivity.kt#L211-L221

I have checked the order and thread this runs in in debug mode and it should work but I don't have a phone that can replicate the issue so it will be helpful if someone can try the latest commit and report back thank you all!

**Comment by hoitab** [comment]
Woohoo! Thanks for confirming it.
